#!/bin/bash
echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the Sleo usb connection as /dev/sleo."
echo ""

sudo cp $(rospack find sleo_bringup)/udev/* /etc/udev/rules.d/ 

echo ""
echo "Restarting udev"
echo ""
sudo udevadm control --reload-rules 
sudo service udev restart 
sudo udevadm trigger
